### PR TITLE
Angular app for displaying sponsors

### PR DESCRIPTION
**Pull request by CuriousLearner**
Angular app made for displaying sponsors of PyDelhi community.

### CODE REVIEW

**Comment by CuriousLearner** [comment]
@theskumar Please let me know if this needs to be changed.

**Comment by theskumar** [comment]
looks good. Possible that you can add a screenshot along to get a visual insight. Thanks.

**Comment by CuriousLearner** [comment]
@theskumar Currently very similar in UI to our talks repo

pydelhi

**Comment by CuriousLearner** [comment]
@theskumar Let me know if this needs to be changed.

**Comment by CuriousLearner** [comment]
@theskumar Haven't got a reply on this from quite a long time. 

Are some changes needed?

**Comment by CuriousLearner** [comment]
Thanks @theskumar :)

**Pull request merged**
